### ISSUE TITLE
problema esp 32 non riesco a copiare

### ISSUE THREAD

**Issue by dipietrofilippo** [Bulduper/HexClock#1]
Ciao, ho un chip esp32, ma utilizzando il programma "visual studio" non riesco a programmare il chip, mi escono tanti errori e non riesco ad andare avanti.
Hai qualche soluzione?
Grazie

**Comment by Bulduper** [comment]
Make sure that you have Platform.io extension installed. Follow the guide [https://kno.wled.ge/advanced/compiling-wled/](https://kno.wled.ge/advanced/compiling-wled/)

**Comment by dipietrofilippo** [comment]
Purtroppo non riesco a programmare il chip con vs studio, ho provato a configurare il software “WLED HEXA CLOCK” ma, come ti ho già detto, mi escono tanti errori, ho provato a configurare il software originale “WLED” purtroppo il risultato è lo stesso.
Mi dispiace perché è un bellissimo progetto e davvero ho voglia di realizzarlo

**Comment by Bulduper** [comment]
You gave practically no information about your errors. If you have issues with uploading the original WLED code, then it is not an issue with the HexaClock modification. Please try to find help on the WLED original repo, the community there is great and you will definitely find the cause. Don't forget to document your problem well!

**Comment by dipietrofilippo** [comment]
Ok grazie mille, domani provo di nuovo e fornisco informazioni più dettagliate
