### ISSUE TITLE
problema per caricare WLED-HexClock

### ISSUE THREAD

**Issue by dipietrofilippo** [Bulduper/HexClock#2]
sto provando a caricare [WLED-HexClock](https://github.com/Bulduper/WLED-HexClock.git), ma sto avendo molti problemi.
vi invio uno screenshot dell'errore che si presenta quando cerco di caricare il repository su Visual Studio Code
![Screenshot (9)](https://github.com/Bulduper/HexaClock/assets/65769357/634f0506-7f52-453e-be74-f86a1c4d60a9)

**Comment by Raabensohn** [comment]
I have the same problem, what did you do?
