### ISSUE TITLE
clock configuration

### ISSUE THREAD

**Issue by dipietrofilippo** [Bulduper/HexClock#3]
hi, I solved all the code installation problems, now I don't understand only one thing, that is, I didn't understand the last step you wrote.

If you see the WLED dashboard, go to /edit path
For each of the following files in the /config folder: cfg.json, ledmap.json, ledmap1.json, presets.json - click Choose file and upload

what should I do?

**Comment by Bulduper** [comment]
Given that your local HexaClock url is http://hexa-clock.local you should visit http://hexa-clock.local/edit
You should see a file browser.
Upload all the files found here: https://github.com/Bulduper/HexaClock/tree/main/config

**Comment by dipietrofilippo** [comment]
Grazie mille, sono riuscito a completare il progetto. E' bellissimo !!!

**Comment by Bulduper** [comment]
I'm glad you did it. I am closing this issue.  @dipietrofilippo could you please share your finished clock (photos or video) on [Instructables](https://www.instructables.com/LED-Hexagon-Wall-Clock/) by clicking `I Made It` in the comment section?

**Comment by dipietrofilippo** [comment]
Ciao, un ultima domanda, ho usato un chip esp32 , non sono riuscito a trovare il pin per inserire il fotoresistore, che consiglio mi puoi dare?
